debug CI [drop]

diff --git a/.github/workflows/lint-test-deploy.yml b/.github/workflows/lint-test-deploy.yml
--- a/.github/workflows/lint-test-deploy.yml
+++ b/.github/workflows/lint-test-deploy.yml
@@ -271,6 +271,7 @@ jobs:
         # Strip "release_" prefix & date suffix from Git tag, set as output.
         # With an invalid tag (e.g. `release_foo_bar`), this fails.
         run: |
+          set -e -u -o pipefail # fail on errors
           sudo apt install --no-install-recommends -qq -y pcre2-utils
           set -x
           cfg="$(echo -n "${{ github.ref_name }}" | pcre2grep -o1 '(?:release_)([\w-]+)(?:_\d{4}-\d{2}-\d{2})')"
@@ -279,33 +280,32 @@ jobs:
       - name: compute Docker image metadata
         id: docker-meta
         run: |
-          set -x
+          set -e -x -u -o pipefail # fail on errors
           echo "image=ghcr.io/${{ github.repository }}" >>$GITHUB_OUTPUT
           echo "permanent-tag=$(date +"%Y-%m-%dT%H.%M.%S")-${GITHUB_SHA:0:7}" >>$GITHUB_OUTPUT
           echo "release-tag=${{ github.ref_name }}" >>$GITHUB_OUTPUT
 
-      # - name: build and push Docker image
-      #   uses: docker/build-push-action@v2
-      #   with:
-      #     context: .
-      #     tags: |
-      #       ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.permanent-tag }}
-      #       ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.release-tag }}
-      #     # https://github.com/docker/build-push-action/blob/9472e9021074a3cb3279ba431598b8836d40433f/docs/advanced/cache.md#github-cache
-      #     # https://github.com/moby/buildkit#registry-push-image-and-cache-separately
-      #     cache-from: type=gha
-      #     cache-to: type=gha,mode=max,oci-mediatypes=true,compression=zstd
-      #     push: true
+      - name: build and push Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          tags: |
+            ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.permanent-tag }}
+            ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.release-tag }}
+          # https://github.com/docker/build-push-action/blob/9472e9021074a3cb3279ba431598b8836d40433f/docs/advanced/cache.md#github-cache
+          # https://github.com/moby/buildkit#registry-push-image-and-cache-separately
+          cache-from: type=gha
+          cache-to: type=gha,mode=max,oci-mediatypes=true,compression=zstd
+          push: true
 
       - name: generate Docker Swarm stack definition
         # todo: secrets through as env vars, such as FAHRGEMEINSCHAFT_API_KEY
         env:
           DOCKER_IMAGE: ${{ steps.docker-meta.outputs.image }}
           DOCKER_TAG: ${{ steps.docker-meta.outputs.permanent-tag }}
+          FAHRGEMEINSCHAFT_API_KEY: ${{ secrets.FAHRGEMEINSCHAFT_API_KEY }}
         run: |
-          env # todo: remove
-          set -x # todo: remove
-          set -e -o pipefail
+          set -e -x -u -o pipefail # fail on errors
           docker-compose \
             -f docker-compose.yml -f deployment/stack.yml \
             -f "deployment/stack.${{ steps.bbnavi-config.outputs.cfg }}.yml" \
@@ -315,12 +315,16 @@ jobs:
         env:
           QUANTUM_ENDPOINT: tpwd-bb-navi
           QUANTUM_PROJECT: bbnavi-digitransit-ui
+          QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
+          QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
         run: |
-          set -x # todo: remove
+          set -e -x -u -o pipefail # fail on errors
           # The "bb-" namespace stands for "Brandenburg", in case we ever have instances in other regions.
-          stack="$QUANTUM_PROJECT-bb-$BBNAVI_CONFIG"
-          env # todo: remove
+          stack="$QUANTUM_PROJECT-bb-${{ steps.bbnavi-config.outputs.cfg }}"
           # todo
-          echo docker run --rm -i \
+          ls -l .quantum
+          docker run --rm -i \
+            -v $PWD:/app:ro -w /app \
+            -e QUANTUM_ENDPOINT -e QUANTUM_PROJECT -e QUANTUM_USER -e QUANTUM_PASSWORD \
             r.planetary-quantum.com/quantum-public/cli:2 \
-            stack update --create --stack "$stack" --wait
+            quantum-cli stack update --create --stack "$stack" --wait
